package gobble

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"

	"github.com/HahyeonJeon/gobble/internal/engine"
	"github.com/HahyeonJeon/gobble/internal/preparation"
)

// PreparationBinding identifies the immutable external facts for a preparation.
type PreparationBinding = preparation.Binding

// PreparedStep is one safe resource/output description in a qualified review.
type PreparedStep = preparation.Step

// PreparedPipeline contains private executable bytes. Never expose Payload to
// ordinary App views, Chat, logs or Agent tools. Review is safe qualified evidence.
type PreparedPipeline struct {
	SchemaVersion int                `json:"schemaVersion"`
	Digest        string             `json:"digest"`
	Payload       json.RawMessage    `json:"payload"`
	Binding       PreparationBinding `json:"binding"`
	Review        json.RawMessage    `json:"review"`
	Steps         []PreparedStep     `json:"steps"`
}

// PreparePipeline seals the exact composed Graph and returns its safe review.
// This operation never launches tasks, claims a workspace or opens research data.
func PreparePipeline(g *Graph, binding PreparationBinding) (*PreparedPipeline, error) {
	if g == nil {
		return nil, errors.New("nil preparation graph")
	}
	if err := composeDefects("prepare", graphCheck(g)); err != nil {
		return nil, err
	}
	doc, err := planDocument(g)
	if err != nil {
		return nil, err
	}
	raw, id, err := engine.Prepare(doc, binding)
	if err != nil {
		return nil, err
	}
	review, err := InspectPipelineCreation(g, binding.InputPath)
	if err != nil {
		return nil, err
	}
	if len(review.Gaps) != 0 {
		return nil, errors.New("the displayed flow is not completely qualified")
	}
	projected, err := json.Marshal(review)
	if err != nil {
		return nil, err
	}
	return &PreparedPipeline{1, id, raw, binding, projected, engine.PreparedSteps(doc)}, nil
}

// ReadPreparationBinding reads only the bounded service-owned descriptor in the
// evaluator's retained source folder. It carries no host paths or credentials.
func ReadPreparationBinding() (PreparationBinding, error) {
	var b PreparationBinding
	f, err := os.Open("gobble-preparation.json")
	if err != nil {
		return b, err
	}
	defer f.Close()
	raw, err := io.ReadAll(io.LimitReader(f, 4097))
	if err != nil || len(raw) > 4096 {
		return b, errors.New("invalid preparation descriptor")
	}
	d := json.NewDecoder(bytes.NewReader(raw))
	d.DisallowUnknownFields()
	if err = d.Decode(&b); err != nil {
		return b, err
	}
	if d.Decode(new(any)) != io.EOF {
		return b, errors.New("trailing preparation descriptor")
	}
	return b, nil
}

// PreparedReview is regenerated by the trusted Gobble reader from sealed bytes.
// Unlike evaluator output, it needs no Project code and carries no private values.
type PreparedReview struct {
	SchemaVersion int                `json:"schemaVersion"`
	Digest        string             `json:"digest"`
	Binding       PreparationBinding `json:"binding"`
	Flow          PipelineInspection `json:"flow"`
	Steps         []PreparedStep     `json:"steps"`
}

// InspectPreparedPipeline decodes exact bytes before deriving the safe review.
// It performs no Project evaluation, workspace mutation, occupancy or task launch.
func InspectPreparedPipeline(raw []byte, id string, b PreparationBinding) (PreparedReview, error) {
	doc, err := engine.DecodePrepared(raw, id, b)
	if err != nil {
		return PreparedReview{}, err
	}
	flow := PipelineInspection{SchemaVersion: 2, Name: doc.Name, Inputs: []PipelinePort{{Name: "reads", Kind: "file", Path: b.InputPath, Members: []PipelineMember{}}}, Steps: []PipelineStep{}, Connections: []PipelineConnection{}}
	for _, task := range doc.Tasks {
		display := TaskDisplay{}
		if task.Display != nil {
			display = TaskDisplay{Stage: task.Display.Stage, Samples: append([]string(nil), task.Display.Samples...), Scope: task.Display.Scope}
		}
		settings := []IntegerSetting{}
		for _, s := range engine.ReviewStep(task).Settings {
			settings = append(settings, IntegerSetting{Key: s.Key, Label: s.Label, Unit: s.Unit, Value: s.Value})
		}
		backend := task.Backend
		if backend == "" {
			backend = "local"
		}
		flow.Steps = append(flow.Steps, PipelineStep{ID: task.ID, Name: task.Name, Module: task.Module, Display: display, Image: task.Image, Backend: backend, CPU: task.Resources.CPU, Memory: task.Resources.Memory, Inputs: inspectionPorts(task.Inputs), Outputs: inspectionPorts(task.Outputs), Settings: settings, Control: PipelineControl{ScatterMembers: []string{}, ScatterMemberPaths: []string{}}})
	}
	for i, e := range doc.Edges {
		flow.Connections = append(flow.Connections, PipelineConnection{ID: fmt.Sprintf("edge-%d", i+1), FromTask: e.FromTask, FromPort: e.FromPort, ToTask: e.ToTask, ToPort: e.ToPort, Wait: append([]string{}, e.Wait...)})
	}
	return PreparedReview{1, id, b, flow, engine.PreparedSteps(doc)}, nil
}
