// Package plothomerannotatepeaks owns one R command that plots HOMER annotation quality control.
package plothomerannotatepeaks

import (
	"strconv"
	"strings"
	"unicode"

	"github.com/HahyeonJeon/gobble"
	"github.com/HahyeonJeon/gobble/assets/modules"
)

// DefaultImage is the nf-core/atacseq 2.1.2 annotation-QC R image resolved for linux/amd64.
const DefaultImage modules.Image = "quay.io/biocontainers/mulled-v2-ad9dd5f398966bf899ae05f8e7c54d0fb10cdfa7:05678da05b8e5a7a5130e90a9f9a6c585b965afa-0@sha256:7965e3c784e5ea0399ddaab5fab08dd916d13e0e5f0a7b47675b4c719149ee7d"

const plotR = `
args <- commandArgs(trailingOnly=TRUE)
if (length(args) < 7 || (length(args) - 5) %% 2 != 0) stop("HOMER QC needs output metadata and matched sample/annotation pairs")
summary_path <- args[[1]]
plot_path <- args[[2]]
multiqc_path <- args[[3]]
multiqc_id <- args[[4]]
multiqc_section <- args[[5]]
labels <- args[seq(6, length(args), by=2)]
paths <- args[seq(7, length(args), by=2)]
if (any(labels == "") || anyDuplicated(labels)) stop("HOMER QC sample labels must be non-empty and unique")
annotations <- lapply(paths, function(path) {
  value <- read.delim(path, header=TRUE, check.names=TRUE, quote="", comment.char="", stringsAsFactors=FALSE)
  required <- c("Annotation", "Distance.to.TSS", "Nearest.PromoterID")
  if (!all(required %in% names(value)) || nrow(value) == 0) stop(paste("invalid or empty HOMER annotation file:", path))
  feature <- sub(" .*", "", value$Annotation)
  distance <- suppressWarnings(abs(as.numeric(value$Distance.to.TSS)))
  promoter <- value$Nearest.PromoterID
  unassigned <- is.na(distance) | is.na(feature) | feature == ""
  distance[unassigned] <- 1000000
  feature[unassigned] <- "Unassigned"
  promoter[is.na(promoter) | promoter == ""] <- "Unassigned"
  data.frame(feature=feature, distance=distance + 1, promoter=promoter, stringsAsFactors=FALSE)
})
names(annotations) <- labels
features <- sort(unique(unlist(lapply(annotations, function(value) value$feature))))
counts <- t(vapply(annotations, function(value) as.integer(table(factor(value$feature, levels=features))), integer(length(features))))
colnames(counts) <- features
summary <- data.frame(sample=labels, counts, check.names=FALSE)
write.table(summary, summary_path, sep="\t", quote=FALSE, row.names=FALSE)
header <- c(
  paste0("# id: '", multiqc_id, "'"),
  paste0("# section_name: '", multiqc_section, "'"),
  "# description: 'Peak annotations generated by HOMER annotatePeaks.pl.'",
  "# plot_type: 'bargraph'",
  paste0("# anchor: '", multiqc_id, "'"),
  "# pconfig:",
  "#     title: 'Peak to feature proportion'",
  "#     ylab: 'Peak count'"
)
body <- capture.output(write.table(summary, sep="\t", quote=FALSE, row.names=FALSE))
writeLines(c(header, body), multiqc_path)
pdf(plot_path, width=max(6, 3 * length(labels)), height=9)
par(mfrow=c(3, 1), mar=c(8, 4, 3, 1))
barplot(t(counts), names.arg=labels, las=2, ylab="Peak count", main="Peak location relative to annotation", legend.text=features)
distance_counts <- t(vapply(annotations, function(value) {
  nearest <- value[order(value$distance), , drop=FALSE]
  nearest <- nearest[!duplicated(nearest$promoter), , drop=FALSE]
  as.integer(table(factor(cut(nearest$distance, breaks=c(-Inf, 2000, 5000, 10000, Inf), labels=c("< 2kb", "< 5kb", "< 10kb", ">= 10kb")), levels=c("< 2kb", "< 5kb", "< 10kb", ">= 10kb"))))
}, integer(4)))
colnames(distance_counts) <- c("< 2kb", "< 5kb", "< 10kb", ">= 10kb")
barplot(t(distance_counts), names.arg=labels, las=2, ylab="Unique genes", main="Distance of closest peak to gene", legend.text=colnames(distance_counts))
boxplot(lapply(annotations, function(value) log10(value$distance)), names=labels, las=2, ylab="log10 distance to TSS", main="Peak distribution relative to TSS")
dev.off()
`

// Options controls one strict HOMER annotation-QC plot command. MultiQCID and
// MultiQCSection identify the declared custom-content artifact.
type Options struct {
	modules.Options
	OutDir         gobble.Directory
	Prefix         string
	MultiQCID      string
	MultiQCSection string
}

// Ports contains the annotation summary, plot document, and MultiQC table.
type Ports struct {
	Summary gobble.Handle
	PDF     gobble.Handle
	MultiQC gobble.Handle
}

// Add records one strict plot command over matched HOMER tables and sample labels.
func Add(parent modules.Parent, annotations []gobble.Handle, labels []string, options Options) (Ports, error) {
	const unit = "plot_homer_annotatepeaks"
	if message := membershipError(annotations, labels); message != "" {
		return Ports{}, modules.ComposeDefect(gobble.DefectInvalidValue, unit, message)
	}
	if len(options.ExtraArgs) != 0 {
		return Ports{}, modules.ComposeDefect(gobble.DefectInvalidValue, unit, "HOMER annotation-QC operands are typed and ExtraArgs are unsupported")
	}
	outDir := options.OutDir
	if outDir.IsZero() {
		outDir = gobble.Dir("results/peak-qc")
	}
	prefix := options.Prefix
	if prefix == "" {
		prefix = "homer_annotation"
	}
	multiQCID := options.MultiQCID
	if multiQCID == "" {
		multiQCID = "peak_annotation"
	}
	multiQCSection := options.MultiQCSection
	if multiQCSection == "" {
		multiQCSection = "HOMER peak annotation"
	}
	if !validMultiQCID(multiQCID) || strings.TrimSpace(multiQCSection) == "" || strings.ContainsAny(multiQCSection, "\r\n'") {
		return Ports{}, modules.ComposeDefect(gobble.DefectInvalidValue, unit, "MultiQC identity or section is invalid")
	}
	summary := gobble.PathSpec{Dir: outDir, Base: prefix, Ext: ".summary.txt"}
	pdf := gobble.PathSpec{Dir: outDir, Base: prefix, Ext: ".plots.pdf"}
	multiQC := gobble.PathSpec{Dir: outDir, Base: prefix, Ext: ".summary_mqc.tsv"}
	summaryPath, err := summary.Render()
	if err != nil {
		return Ports{}, modules.ComposeDefect(gobble.DefectInvalidPath, unit, "HOMER annotation-QC output path is invalid")
	}
	pdfPath, err := pdf.Render()
	if err != nil {
		return Ports{}, modules.ComposeDefect(gobble.DefectInvalidPath, unit, "HOMER annotation-QC output path is invalid")
	}
	multiQCPath, err := multiQC.Render()
	if err != nil {
		return Ports{}, modules.ComposeDefect(gobble.DefectInvalidPath, unit, "HOMER annotation-QC output path is invalid")
	}
	command := []string{"Rscript", "-e", plotR, summaryPath, pdfPath, multiQCPath, multiQCID, multiQCSection}
	inputs := make([]gobble.Bind, len(annotations))
	for i, annotation := range annotations {
		path, pathErr := modules.HandlePath(unit, annotation)
		if pathErr != nil {
			return Ports{}, pathErr
		}
		command = append(command, labels[i], path)
		inputs[i] = gobble.Bind{Name: "annotation_" + strconv.Itoa(i), From: annotation}
	}
	base := options.Options
	base.ExtraArgs = nil
	command, image, resources, err := modules.ResolveOptions(unit, base, DefaultImage, gobble.Resources{CPU: 2, Memory: "4g"}, command, []string{"-e"})
	if err != nil {
		return Ports{}, err
	}
	task := parent.AddTask(gobble.TaskSpec{Name: unit, Command: command, Image: image, Resources: resources, Inputs: inputs, Outputs: []gobble.Bind{{Name: "summary", Spec: summary}, {Name: "pdf", Spec: pdf}, {Name: "multiqc", Spec: multiQC}}})
	return Ports{Summary: task.Out("summary"), PDF: task.Out("pdf"), MultiQC: task.Out("multiqc")}, nil
}

// Pipeline returns a standalone validated HOMER annotation-QC plot module.
func Pipeline(annotations []gobble.PathSpec, labels []string, options Options) *gobble.Pipeline {
	inputs := make([]modules.Input, len(annotations))
	for i, annotation := range annotations {
		inputs[i] = modules.Input{Name: "annotation_" + strconv.Itoa(i), Spec: annotation}
	}
	return modules.StandaloneChecked("plot-homer-annotatepeaks", inputs, func(parent modules.Parent, handles []gobble.Handle) error {
		_, err := Add(parent, handles, append([]string(nil), labels...), options)
		return err
	})
}

func membershipError(annotations []gobble.Handle, labels []string) string {
	if len(annotations) == 0 || len(annotations) != len(labels) {
		return "annotation and sample-label membership must be non-empty and equal"
	}
	seen := make(map[string]bool, len(labels))
	for _, label := range labels {
		if strings.TrimSpace(label) == "" || strings.ContainsAny(label, "\r\n\t") || seen[label] {
			return "sample labels must be non-empty and unique"
		}
		seen[label] = true
	}
	return ""
}

func validMultiQCID(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' && r != '-' {
			return false
		}
	}
	return true
}
